package com.totalplay.alarmtype.tprovisioningux;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-15T13:32:30.733-06:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "BPELSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BPELSoap {

   
    /**
     * Obtiene Alarmas ONT por IP
     */
    @WebMethod(operationName = "BPELGetAllPortAlarmByIp", action = "http://tempuri.org/BPELGetAllPortAlarmByIp")
    @RequestWrapper(localName = "BPELGetAllPortAlarmByIp", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BPELGetAllPortAlarmByIp")
    @ResponseWrapper(localName = "BPELGetAllPortAlarmByIpResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BPELGetAllPortAlarmByIpResponse")
    @WebResult(name = "BPELGetAllPortAlarmByIpResult", targetNamespace = "http://tempuri.org/")
    public com.totalplay.alarmtype.tprovisioningux.ArrayOfONTAlarm bpelGetAllPortAlarmByIp(

        @WebParam(name = "Frame", targetNamespace = "http://tempuri.org/")
        int frame,
        @WebParam(name = "Slot", targetNamespace = "http://tempuri.org/")
        int slot,
        @WebParam(name = "Port", targetNamespace = "http://tempuri.org/")
        int port,
        @WebParam(name = "IPOLT", targetNamespace = "http://tempuri.org/")
        java.lang.String ipolt
    );

    /**
     * Obtiene Alarmas ONT por IP
     */
    @WebMethod(operationName = "BPELGetPersonalAlarm", action = "http://tempuri.org/BPELGetPersonalAlarm")
    @RequestWrapper(localName = "BPELGetPersonalAlarm", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BPELGetPersonalAlarm")
    @ResponseWrapper(localName = "BPELGetPersonalAlarmResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BPELGetPersonalAlarmResponse")
    @WebResult(name = "BPELGetPersonalAlarmResult", targetNamespace = "http://tempuri.org/")
    public int bpelGetPersonalAlarm(

        @WebParam(name = "Frame", targetNamespace = "http://tempuri.org/")
        int frame,
        @WebParam(name = "Slot", targetNamespace = "http://tempuri.org/")
        int slot,
        @WebParam(name = "Port", targetNamespace = "http://tempuri.org/")
        int port,
        @WebParam(name = "NomOlt", targetNamespace = "http://tempuri.org/")
        java.lang.String nomOlt,
        @WebParam(name = "OntID", targetNamespace = "http://tempuri.org/")
        int ontID,
        @WebParam(name = "Alias", targetNamespace = "http://tempuri.org/")
        java.lang.String alias
    );

   
}
